#include <iostream>

#include "Beverage.h"
#include "BeverageDecorator.h"
#include "Sugar.h"
#include "WhippedCream.h"
#include "GreenTea.h"
#include "Milk.h"
#include "Order.h"
#include "OrderFactory.h"
#include "Caramel.h"
#include "MobileOrder.h"
#include "Latte.h"
#include "Espresso.h"
#include "CashierOrder.h"
#include "PresetRegistry.h"
